/*   1:    */ package gregtech.loaders.preload;
/*   2:    */ 
/*   3:    */ import gregtech.api.util.GT_Log;
/*   4:    */ import gregtech.loaders.oreprocessing.ProcessingAll;
/*   5:    */ import gregtech.loaders.oreprocessing.ProcessingArrows;
/*   6:    */ import gregtech.loaders.oreprocessing.ProcessingBattery;
/*   7:    */ import gregtech.loaders.oreprocessing.ProcessingBeans;
/*   8:    */ import gregtech.loaders.oreprocessing.ProcessingBlock;
/*   9:    */ import gregtech.loaders.oreprocessing.ProcessingBolt;
/*  10:    */ import gregtech.loaders.oreprocessing.ProcessingCell;
/*  11:    */ import gregtech.loaders.oreprocessing.ProcessingCellPlasma;
/*  12:    */ import gregtech.loaders.oreprocessing.ProcessingCircuit;
/*  13:    */ import gregtech.loaders.oreprocessing.ProcessingCompressed;
/*  14:    */ import gregtech.loaders.oreprocessing.ProcessingCrafting;
/*  15:    */ import gregtech.loaders.oreprocessing.ProcessingCrop;
/*  16:    */ import gregtech.loaders.oreprocessing.ProcessingCrushedCentrifuged;
/*  17:    */ import gregtech.loaders.oreprocessing.ProcessingCrushedPurified;
/*  18:    */ import gregtech.loaders.oreprocessing.ProcessingCrystallized;
/*  19:    */ import gregtech.loaders.oreprocessing.ProcessingDirty;
/*  20:    */ import gregtech.loaders.oreprocessing.ProcessingDust;
/*  21:    */ import gregtech.loaders.oreprocessing.ProcessingDustImpure;
/*  22:    */ import gregtech.loaders.oreprocessing.ProcessingDustSmall;
/*  23:    */ import gregtech.loaders.oreprocessing.ProcessingDustTiny;
/*  24:    */ import gregtech.loaders.oreprocessing.ProcessingDye;
/*  25:    */ import gregtech.loaders.oreprocessing.ProcessingFoil;
/*  26:    */ import gregtech.loaders.oreprocessing.ProcessingFood;
/*  27:    */ import gregtech.loaders.oreprocessing.ProcessingGear;
/*  28:    */ import gregtech.loaders.oreprocessing.ProcessingGearSmall;
/*  29:    */ import gregtech.loaders.oreprocessing.ProcessingGem;
/*  30:    */ import gregtech.loaders.oreprocessing.ProcessingGemChipped;
/*  31:    */ import gregtech.loaders.oreprocessing.ProcessingGemExquisite;
/*  32:    */ import gregtech.loaders.oreprocessing.ProcessingGemFlawed;
/*  33:    */ import gregtech.loaders.oreprocessing.ProcessingGemFlawless;
/*  34:    */ import gregtech.loaders.oreprocessing.ProcessingIngot1;
/*  35:    */ import gregtech.loaders.oreprocessing.ProcessingIngot2;
/*  36:    */ import gregtech.loaders.oreprocessing.ProcessingIngot3;
/*  37:    */ import gregtech.loaders.oreprocessing.ProcessingIngot4;
/*  38:    */ import gregtech.loaders.oreprocessing.ProcessingIngot5;
/*  39:    */ import gregtech.loaders.oreprocessing.ProcessingIngotHot;
/*  40:    */ import gregtech.loaders.oreprocessing.ProcessingItem;
/*  41:    */ import gregtech.loaders.oreprocessing.ProcessingLeaves;
/*  42:    */ import gregtech.loaders.oreprocessing.ProcessingLens;
/*  43:    */ import gregtech.loaders.oreprocessing.ProcessingLog;
/*  44:    */ import gregtech.loaders.oreprocessing.ProcessingNugget;
/*  45:    */ import gregtech.loaders.oreprocessing.ProcessingOre;
/*  46:    */ import gregtech.loaders.oreprocessing.ProcessingOrePoor;
/*  47:    */ import gregtech.loaders.oreprocessing.ProcessingOreSmelting;
/*  48:    */ import gregtech.loaders.oreprocessing.ProcessingPipeLarge;
/*  49:    */ import gregtech.loaders.oreprocessing.ProcessingPipeMedium;
/*  50:    */ import gregtech.loaders.oreprocessing.ProcessingPipeRestrictive;
/*  51:    */ import gregtech.loaders.oreprocessing.ProcessingPipeSmall;
/*  52:    */ import gregtech.loaders.oreprocessing.ProcessingPlank;
/*  53:    */ import gregtech.loaders.oreprocessing.ProcessingPlate1;
/*  54:    */ import gregtech.loaders.oreprocessing.ProcessingPlate2;
/*  55:    */ import gregtech.loaders.oreprocessing.ProcessingPlate3;
/*  56:    */ import gregtech.loaders.oreprocessing.ProcessingPlate4;
/*  57:    */ import gregtech.loaders.oreprocessing.ProcessingPlate5;
/*  58:    */ import gregtech.loaders.oreprocessing.ProcessingPlate9;
/*  59:    */ import gregtech.loaders.oreprocessing.ProcessingPlateAlloy;
/*  60:    */ import gregtech.loaders.oreprocessing.ProcessingPure;
/*  61:    */ import gregtech.loaders.oreprocessing.ProcessingRecycling;
/*  62:    */ import gregtech.loaders.oreprocessing.ProcessingSand;
/*  63:    */ import gregtech.loaders.oreprocessing.ProcessingSaplings;
/*  64:    */ import gregtech.loaders.oreprocessing.ProcessingShaping;
/*  65:    */ import gregtech.loaders.oreprocessing.ProcessingSlab;
/*  66:    */ import gregtech.loaders.oreprocessing.ProcessingStick;
/*  67:    */ import gregtech.loaders.oreprocessing.ProcessingStickLong;
/*  68:    */ import gregtech.loaders.oreprocessing.ProcessingStone;
/*  69:    */ import gregtech.loaders.oreprocessing.ProcessingStoneCobble;
/*  70:    */ import gregtech.loaders.oreprocessing.ProcessingStoneVarious;
/*  71:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadArrow;
/*  72:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadAxe;
/*  73:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadBuzzSaw;
/*  74:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadChainsaw;
/*  75:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadDrill;
/*  76:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadFile;
/*  77:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadHammer;
/*  78:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadHoe;
/*  79:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadPickaxe;
/*  80:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadPlow;
/*  81:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadSaw;
/*  82:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadSense;
/*  83:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadShovel;
/*  84:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadSword;
/*  85:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadUniversalSpade;
/*  86:    */ import gregtech.loaders.oreprocessing.ProcessingToolHeadWrench;
/*  87:    */ import gregtech.loaders.oreprocessing.ProcessingTransforming;
/*  88:    */ import gregtech.loaders.oreprocessing.ProcessingWax;
/*  89:    */ import gregtech.loaders.oreprocessing.ProcessingWire01;
/*  90:    */ import gregtech.loaders.oreprocessing.ProcessingWire02;
/*  91:    */ import gregtech.loaders.oreprocessing.ProcessingWire04;
/*  92:    */ import gregtech.loaders.oreprocessing.ProcessingWire08;
/*  93:    */ import gregtech.loaders.oreprocessing.ProcessingWire12;
/*  94:    */ import gregtech.loaders.oreprocessing.ProcessingWire16;
/*  95:    */ import java.io.PrintStream;
/*  96:    */ 
/*  97:    */ public class GT_Loader_OreProcessing
/*  98:    */   implements Runnable
/*  99:    */ {
/* 100:    */   public void run()
/* 101:    */   {
/* 102:  9 */     GT_Log.out.println("GT_Mod: Register Ore processing.");
/* 103: 10 */     new ProcessingAll();
/* 104: 11 */     new ProcessingArrows();
/* 105: 12 */     new ProcessingBattery();
/* 106: 13 */     new ProcessingBeans();
/* 107: 14 */     new ProcessingBlock();
/* 108: 15 */     new ProcessingBolt();
/* 109: 16 */     new ProcessingCell();
/* 110: 17 */     new ProcessingCellPlasma();
/* 111: 18 */     new ProcessingCircuit();
/* 112: 19 */     new ProcessingCompressed();
/* 113: 20 */     new ProcessingCrafting();
/* 114: 21 */     new ProcessingCrop();
/* 115: 22 */     new ProcessingCrushedPurified();
/* 116: 23 */     new ProcessingCrushedCentrifuged();
/* 117: 24 */     new ProcessingCrystallized();
/* 118: 25 */     new ProcessingDirty();
/* 119: 26 */     new ProcessingDust();
/* 120: 27 */     new ProcessingDustImpure();
/* 121: 28 */     new ProcessingDustSmall();
/* 122: 29 */     new ProcessingDustTiny();
/* 123: 30 */     new ProcessingDye();
/* 124: 31 */     new ProcessingFoil();
/* 125: 32 */     new ProcessingFood();
/* 126: 33 */     new ProcessingLens();
/* 127: 34 */     new ProcessingShaping();
/* 128: 35 */     new ProcessingGemChipped();
/* 129: 36 */     new ProcessingGemFlawed();
/* 130: 37 */     new ProcessingGem();
/* 131: 38 */     new ProcessingGemFlawless();
/* 132: 39 */     new ProcessingGemExquisite();
/* 133: 40 */     new ProcessingGear();
/* 134: 41 */     new ProcessingGearSmall();
/* 135: 42 */     new ProcessingIngot1();
/* 136: 43 */     new ProcessingIngot2();
/* 137: 44 */     new ProcessingIngot3();
/* 138: 45 */     new ProcessingIngot4();
/* 139: 46 */     new ProcessingIngot5();
/* 140: 47 */     new ProcessingIngotHot();
/* 141: 48 */     new ProcessingItem();
/* 142: 49 */     new ProcessingLeaves();
/* 143: 50 */     new ProcessingLog();
/* 144: 51 */     new ProcessingTransforming();
/* 145: 52 */     new ProcessingNugget();
/* 146: 53 */     new ProcessingOre();
/* 147: 54 */     new ProcessingOrePoor();
/* 148: 55 */     new ProcessingOreSmelting();
/* 149: 56 */     new ProcessingPipeSmall();
/* 150: 57 */     new ProcessingPipeMedium();
/* 151: 58 */     new ProcessingPipeLarge();
/* 152: 59 */     new ProcessingPipeRestrictive();
/* 153: 60 */     new ProcessingPlank();
/* 154: 61 */     new ProcessingPlate1();
/* 155: 62 */     new ProcessingPlate2();
/* 156: 63 */     new ProcessingPlate3();
/* 157: 64 */     new ProcessingPlate4();
/* 158: 65 */     new ProcessingPlate5();
/* 159: 66 */     new ProcessingPlate9();
/* 160: 67 */     new ProcessingPlateAlloy();
/* 161: 68 */     new ProcessingPure();
/* 162: 69 */     new ProcessingRecycling();
/* 163: 70 */     new ProcessingSand();
/* 164: 71 */     new ProcessingSaplings();
/* 165: 72 */     new ProcessingSlab();
/* 166: 73 */     new ProcessingStick();
/* 167: 74 */     new ProcessingStickLong();
/* 168: 75 */     new ProcessingStone();
/* 169: 76 */     new ProcessingStoneCobble();
/* 170: 77 */     new ProcessingStoneVarious();
/* 171: 78 */     new ProcessingToolHeadArrow();
/* 172: 79 */     new ProcessingToolHeadAxe();
/* 173: 80 */     new ProcessingToolHeadBuzzSaw();
/* 174: 81 */     new ProcessingToolHeadFile();
/* 175: 82 */     new ProcessingToolHeadHammer();
/* 176: 83 */     new ProcessingToolHeadHoe();
/* 177: 84 */     new ProcessingToolHeadPickaxe();
/* 178: 85 */     new ProcessingToolHeadSaw();
/* 179: 86 */     new ProcessingToolHeadSense();
/* 180: 87 */     new ProcessingToolHeadShovel();
/* 181: 88 */     new ProcessingToolHeadSword();
/* 182: 89 */     new ProcessingToolHeadPlow();
/* 183: 90 */     new ProcessingToolHeadDrill();
/* 184: 91 */     new ProcessingToolHeadChainsaw();
/* 185: 92 */     new ProcessingToolHeadWrench();
/* 186: 93 */     new ProcessingToolHeadUniversalSpade();
/* 187: 94 */     new ProcessingWax();
/* 188: 95 */     new ProcessingWire01();
/* 189: 96 */     new ProcessingWire02();
/* 190: 97 */     new ProcessingWire04();
/* 191: 98 */     new ProcessingWire08();
/* 192: 99 */     new ProcessingWire12();
/* 193:100 */     new ProcessingWire16();
/* 194:    */   }
/* 195:    */ }


/* Location:           F:\Torrent\minecraft\jd-gui-0.3.6.windows\gregtech_1.7.10-5.07.07-dev.jar
 * Qualified Name:     gregtech.loaders.preload.GT_Loader_OreProcessing
 * JD-Core Version:    0.7.0.1
 */