package gregtech.loaders.oreprocessing;

import gregtech.api.GT_Values;
import gregtech.api.items.ItemList;
import gregtech.api.items.ToolDictNames;
import gregtech.api.recipes.ModHandler;
import gregtech.api.unification.OreDictionaryUnifier;
import gregtech.api.unification.material.Materials;
import gregtech.api.unification.ore.IOreRegistrationHandler;
import gregtech.api.unification.ore.OrePrefix;
import gregtech.api.unification.stack.SimpleItemStack;
import gregtech.api.unification.stack.UnificationEntry;
import gregtech.api.util.GT_Utility;
import gregtech.common.GT_Proxy;
import gregtech.common.items.MetaTool;
import net.minecraft.item.ItemStack;

public class ProcessingToolHead implements IOreRegistrationHandler {
    public ProcessingToolHead() {
        OrePrefix.toolHeadArrow.addProcessingHandler(this);
        OrePrefix.toolHeadAxe.addProcessingHandler(this);
        OrePrefix.toolHeadBuzzSaw.addProcessingHandler(this);
        OrePrefix.toolHeadChainsaw.addProcessingHandler(this);
        OrePrefix.toolHeadDrill.addProcessingHandler(this);
        OrePrefix.toolHeadFile.addProcessingHandler(this);
        OrePrefix.toolHeadHoe.addProcessingHandler(this);
        OrePrefix.toolHeadPickaxe.addProcessingHandler(this);
        OrePrefix.toolHeadPlow.addProcessingHandler(this);
        OrePrefix.toolHeadSaw.addProcessingHandler(this);
        OrePrefix.toolHeadSense.addProcessingHandler(this);
        OrePrefix.toolHeadShovel.addProcessingHandler(this);
        OrePrefix.toolHeadSword.addProcessingHandler(this);
        OrePrefix.toolHeadUniversalSpade.addProcessingHandler(this);
        OrePrefix.toolHeadWrench.addProcessingHandler(this);
        OrePrefix.toolHeadHammer.addProcessingHandler(this);
        OrePrefix.turbineBlade.addProcessingHandler(this);
    }

    @Override
    public void registerOre(UnificationEntry uEntry, String modName, SimpleItemStack simpleStack) {
        ItemStack stack = simpleStack.asItemStack();
        boolean aSpecialRecipeReq1 = uEntry.material.mUnificatable && (uEntry.material.mMaterialInto == uEntry.material) && !uEntry.material.contains(SubTag.NO_SMASHING);
        boolean aSpecialRecipeReq2 = uEntry.material.mUnificatable && (uEntry.material.mMaterialInto == uEntry.material) && !uEntry.material.contains(SubTag.NO_WORKING);
        boolean aNoWorking = uEntry.material.contains(SubTag.NO_WORKING);

        switch (uEntry.orePrefix) {
            case toolHeadArrow:
                if (uEntry.material.mStandardMoltenFluid != null)
                    GT_Values.RA.addFluidSolidifierRecipe(ItemList.Shape_Mold_Arrow.get(0), uEntry.material.getMolten(36L), GT_Utility.copyAmount(1, stack), 16, 4);
                if (aSpecialRecipeReq2) {
                    ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadArrow, uEntry.material, 1L), GT_Proxy.tBits, new Object[]{"Xf", 'X', OrePrefix.gemChipped.get(uEntry.material)});
                    ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadArrow, uEntry.material, 3L), GT_Proxy.tBits, new Object[]{(uEntry.material.contains(SubTag.WOOD) ? 115 : 'x') + "Pf", 'P', OrePrefix.plate.get(uEntry.material)});
                }
                break;
            case toolHeadAxe:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.AXE, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadAxe, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"PIh", "P  ", "f  ", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadAxe, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"GG ", "G  ", "f  ", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadBuzzSaw:
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.BUZZSAW, 1, uEntry.material, Materials.StainlessSteel, new long[]{100000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"PBM", "dXG", "SGP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.BUZZSAW, 1, uEntry.material, Materials.StainlessSteel, new long[]{75000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"PBM", "dXG", "SGP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.BUZZSAW, 1, uEntry.material, Materials.StainlessSteel, new long[]{50000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"PBM", "dXG", "SGP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Sodium.get(1)});
                if (aSpecialRecipeReq2) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadBuzzSaw, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"wXh", "X X", "fXx", 'X', OrePrefix.plate.get(uEntry.material)});
                break;
            case toolHeadChainsaw:
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{100000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_MV, 1, uEntry.material, Materials.Titanium, new long[]{400000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{1600000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{75000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_MV, 1, uEntry.material, Materials.Titanium, new long[]{300000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{1200000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{50000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_MV, 1, uEntry.material, Materials.Titanium, new long[]{200000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.CHAINSAW_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{800000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Sodium.get(1)});
                if (aSpecialRecipeReq2) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadChainsaw, uEntry.material, 1L), GT_Proxy.tBits, new Object[]{"SRS", "XhX", "SRS", 'X', OrePrefix.plate.get(uEntry.material), 'S', OrePrefix.plate.get(Materials.Steel), 'R', OrePrefix.ring.get(Materials.Steel)});
                break;
            case toolHeadDrill:
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{100000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{75000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{50000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_MV, 1, uEntry.material, Materials.Titanium, new long[]{400000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_MV, 1, uEntry.material, Materials.Titanium, new long[]{300000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_MV, 1, uEntry.material, Materials.Titanium, new long[]{200000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{1600000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{1200000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.DRILL_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{800000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.JACKHAMMER, 1, uEntry.material, Materials.Titanium, new long[]{1600000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "PRP", "MPB", 'X', OrePrefix.stickLong.get(uEntry.material), 'M', ItemList.Electric_Piston_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'R', OrePrefix.spring.get(Materials.Titanium), 'B', ItemList.Battery_RE_HV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.JACKHAMMER, 1, uEntry.material, Materials.Titanium, new long[]{1200000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "PRP", "MPB", 'X', OrePrefix.stickLong.get(uEntry.material), 'M', ItemList.Electric_Piston_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'R', OrePrefix.spring.get(Materials.Titanium), 'B', ItemList.Battery_RE_HV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.JACKHAMMER, 1, uEntry.material, Materials.Titanium, new long[]{800000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "PRP", "MPB", 'X', OrePrefix.stickLong.get(uEntry.material), 'M', ItemList.Electric_Piston_HV.get(1L, new Object[0]), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'R', OrePrefix.spring.get(Materials.Titanium), 'B', ItemList.Battery_RE_HV_Sodium.get(1)});
                if (aSpecialRecipeReq2) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadDrill, uEntry.material, 1L), GT_Proxy.tBits, new Object[]{"XSX", "XSX", "ShS", 'X', OrePrefix.plate.get(uEntry.material), 'S', OrePrefix.plate.get(Materials.Steel)});
                break;
            case toolHeadFile:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.FILE, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if ((!uEntry.material.contains(SubTag.NO_SMASHING)) && (!uEntry.material.contains(SubTag.BOUNCY))) {
                    ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.FILE, 1, uEntry.material, uEntry.material.mHandleMaterial, null), ModHandler.RecipeBits.MIRRORED | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"P", "P", "S", 'P', OrePrefix.plate.get(uEntry.material), 'S', OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                }
                break;
            case toolHeadHoe:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.HOE, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadHoe, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"PIh", "f  ", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadHoe, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"GG ", "f  ", "   ", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadPickaxe:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.PICKAXE, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadPickaxe, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"PII", "f h", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadPickaxe, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"GGG", "f  ", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadPlow:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.PLOW, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadPlow, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"PP", "PP", "hf", 'P', OrePrefix.plate.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadPlow, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"GG", "GG", " f", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadSaw:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SAW, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadSaw, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"PP ", "fh ", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadSaw, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"GGf", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadSense:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SENSE, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadSense, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"PPI", "hf ", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadSense, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"GGG", " f ", "   ", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadShovel:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SHOVEL, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadShovel, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"fPh", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadShovel, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"fG", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadSword:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SWORD, 1, uEntry.material, uEntry.material.mHandleMaterial, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadSword, uEntry.material, 1), GT_Proxy.tBits, new Object[]{" P ", "fPh", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                if (!aNoWorking) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadSword, uEntry.material, 1), GT_Proxy.tBits, new Object[]{" G", "fG", 'G', OrePrefix.gem.get(uEntry.material)});
                break;
            case toolHeadUniversalSpade:
                ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.UNIVERSALSPADE, 1, uEntry.material, uEntry.material, null), new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material), OrePrefix.screw.get(uEntry.material), ToolDictNames.craftingToolScrewdriver});
                if (aSpecialRecipeReq2) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadUniversalSpade, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"fX", 'X', OrePrefix.toolHeadShovel.get(uEntry.material)});
                break;
            case toolHeadWrench:
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{100000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_MV, 1, uEntry.material, Materials.Titanium, new long[]{400000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{1600000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{75000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_MV, 1, uEntry.material, Materials.Titanium, new long[]{300000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{1200000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{50000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_LV.get(1), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_MV, 1, uEntry.material, Materials.Titanium, new long[]{200000L, 128L, 2L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_MV.get(1), 'S', OrePrefix.screw.get(Materials.Titanium), 'P', OrePrefix.plate.get(Materials.Titanium), 'G', OrePrefix.gearGtSmall.get(Materials.Titanium), 'B', ItemList.Battery_RE_MV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.WRENCH_HV, 1, uEntry.material, Materials.TungstenSteel, new long[]{800000L, 512L, 3L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"SXd", "GMG", "PBP", 'X', aOreDictName, 'M', ItemList.Electric_Motor_HV.get(1), 'S', OrePrefix.screw.get(Materials.TungstenSteel), 'P', OrePrefix.plate.get(Materials.TungstenSteel), 'G', OrePrefix.gearGtSmall.get(Materials.TungstenSteel), 'B', ItemList.Battery_RE_HV_Sodium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SCREWDRIVER_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{100000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"PdX", "MGS", "GBP", 'X', OrePrefix.stickLong.get(uEntry.material), 'M', ItemList.Electric_Motor_LV.get(1), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Lithium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SCREWDRIVER_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{75000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"PdX", "MGS", "GBP", 'X', OrePrefix.stickLong.get(uEntry.material), 'M', ItemList.Electric_Motor_LV.get(1), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Cadmium.get(1)});
                ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats(MetaTool.SCREWDRIVER_LV, 1, uEntry.material, Materials.StainlessSteel, new long[]{50000L, 32L, 1L, -1L}), ModHandler.RecipeBits.DISMANTLEABLE | ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"PdX", "MGS", "GBP", 'X', OrePrefix.stickLong.get(uEntry.material), 'M', ItemList.Electric_Motor_LV.get(1), 'S', OrePrefix.screw.get(Materials.StainlessSteel), 'P', OrePrefix.plate.get(Materials.StainlessSteel), 'G', OrePrefix.gearGtSmall.get(Materials.StainlessSteel), 'B', ItemList.Battery_RE_LV_Sodium.get(1)});
                if (aSpecialRecipeReq2) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadWrench, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"hXW", "XRX", "WXd", 'X', OrePrefix.plate.get(uEntry.material), 'S', OrePrefix.plate.get(Materials.Steel), 'R', OrePrefix.ring.get(Materials.Steel), 'W', OrePrefix.screw.get(Materials.Steel)});
                break;
            case toolHeadHammer:
                if ((uEntry.material != Materials.Stone) && (uEntry.material != Materials.Flint)) {
                    ModHandler.addShapelessCraftingRecipe(MetaTool.INSTANCE.getToolWithStats((uEntry.material.contains(SubTag.BOUNCY)) || (uEntry.material.contains(SubTag.WOOD)) ? MetaTool.SOFTHAMMER : MetaTool.HARDHAMMER, 1, uEntry.material, uEntry.material.mHandleMaterial, null), ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{aOreDictName, OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                    ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats((uEntry.material.contains(SubTag.BOUNCY)) || (uEntry.material.contains(SubTag.WOOD)) ? MetaTool.SOFTHAMMER : MetaTool.HARDHAMMER, 1, uEntry.material, uEntry.material.mHandleMaterial, null), ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"XX ", "XXS", "XX ", 'X', uEntry.material == Materials.Wood ? OrePrefix.plank.get(Materials.Wood) : OrePrefix.ingot.get(uEntry.material), 'S', OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                    ModHandler.addCraftingRecipe(MetaTool.INSTANCE.getToolWithStats((uEntry.material.contains(SubTag.BOUNCY)) || (uEntry.material.contains(SubTag.WOOD)) ? MetaTool.SOFTHAMMER : MetaTool.HARDHAMMER, 1, uEntry.material, uEntry.material.mHandleMaterial, null), ModHandler.RecipeBits.DO_NOT_CHECK_FOR_COLLISIONS | ModHandler.RecipeBits.BUFFERED, new Object[]{"XX ", "XXS", "XX ", 'X', uEntry.material == Materials.Wood ? OrePrefix.plank.get(Materials.Wood) : OrePrefix.gem.get(uEntry.material), 'S', OrePrefix.stick.get(uEntry.material.mHandleMaterial)});
                }
                if (uEntry.orePrefix == OrePrefix.toolHeadHammer)
                    if (aSpecialRecipeReq1) ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.toolHeadHammer, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"II ", "IIh", "II ", 'P', OrePrefix.plate.get(uEntry.material), 'I', OrePrefix.ingot.get(uEntry.material)});
                break;
            case turbineBlade:
                GT_Values.RA.addAssemblerRecipe(OreDictionaryUnifier.get(OrePrefix.turbineBlade, uEntry.material, 4), OreDictionaryUnifier.get(OrePrefix.stickLong, Materials.Magnalium, 1L), MetaTool.INSTANCE.getToolWithStats(170, 1, uEntry.material, uEntry.material, null), 160, 100);
                GT_Values.RA.addAssemblerRecipe(OreDictionaryUnifier.get(OrePrefix.turbineBlade, uEntry.material, 8), OreDictionaryUnifier.get(OrePrefix.stickLong, Materials.Titanium, 1L), MetaTool.INSTANCE.getToolWithStats(172, 1, uEntry.material, uEntry.material, null), 320, 400);
                GT_Values.RA.addAssemblerRecipe(OreDictionaryUnifier.get(OrePrefix.turbineBlade, uEntry.material, 12), OreDictionaryUnifier.get(OrePrefix.stickLong, Materials.TungstenSteel, 1L), MetaTool.INSTANCE.getToolWithStats(174, 1, uEntry.material, uEntry.material, null), 640, 1600);
                GT_Values.RA.addAssemblerRecipe(OreDictionaryUnifier.get(OrePrefix.turbineBlade, uEntry.material, 16), OreDictionaryUnifier.get(OrePrefix.stickLong, Materials.Americium, 1L), MetaTool.INSTANCE.getToolWithStats(176, 1, uEntry.material, uEntry.material, null), 1280, 6400);
                if (aSpecialRecipeReq2) {
                    ModHandler.addCraftingRecipe(OreDictionaryUnifier.get(OrePrefix.turbineBlade, uEntry.material, 1), GT_Proxy.tBits, new Object[]{"fPd", "SPS", " P ", 'P', uEntry.material == Materials.Wood ? OrePrefix.plank.get(uEntry.material) : OrePrefix.plateDouble.get(uEntry.material), 'R', OrePrefix.ring.get(uEntry.material), 'S', OrePrefix.screw.get(uEntry.material)});
                }
                break;
        }
    }
}
