package gregtech.loaders.preload;

import gregtech.api.recipes.ModHandler;
import gregtech.api.unification.OreDictUnifier;
import gregtech.api.unification.material.Materials;
import gregtech.api.unification.ore.OrePrefix;
import gregtech.api.unification.stack.ItemMaterialInfo;
import gregtech.api.unification.stack.MaterialStack;
import gregtech.api.util.GTLog;
import ic2.core.item.type.CasingResourceType;
import ic2.core.item.type.NuclearResourceType;
import ic2.core.ref.ItemName;
import ic2.core.ref.TeBlock;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

import static gregtech.api.GTValues.M;
import static gregtech.api.GTValues.W;

public class MaterialInfoLoader implements Runnable {
    
    public void run() {
        //GTLog.logger.info("Loading Item Data Tags");
        //OreDictUnifier.registerOre(ModHandler.getModItem("TwilightForest", "item.giantPick", 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 696729600L), new MaterialStack(Materials.Wood, 464486400L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("TwilightForest", "item.giantSword", 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 464486400L), new MaterialStack(Materials.Wood, 232243200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("TwilightForest", "tile.GiantLog", 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 232243200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("TwilightForest", "tile.GiantCobble", 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 232243200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("TwilightForest", "tile.GiantObsidian", 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Obsidian, 232243200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("TwilightForest", "item.minotaurAxe", 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Diamond, 14515200L), new MaterialStack(Materials.Wood, OrePrefix.stick.materialAmount * 2L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 10), new ItemMaterialInfo(new MaterialStack(Materials.CertusQuartz, 1814400L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("appliedenergistics2", "item.ItemMultiMaterial", 1, 11), new ItemMaterialInfo(new MaterialStack(Materials.NetherQuartz, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.QUARTZ_BLOCK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.NetherQuartz, 14515200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("appliedenergistics2", "tile.BlockQuartz", 1, W), new ItemMaterialInfo(new MaterialStack(Materials.CertusQuartz, 14515200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("appliedenergistics2", "tile.BlockQuartzPillar", 1, W), new ItemMaterialInfo(new MaterialStack(Materials.CertusQuartz, 14515200L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("appliedenergistics2", "tile.BlockQuartzChiseled", 1, W), new ItemMaterialInfo(new MaterialStack(Materials.CertusQuartz, 14515200L)));
        OreDictUnifier.registerOre(new ItemStack(Items.WHEAT, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wheat, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.HAY_BLOCK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wheat, 32659200L)));
        OreDictUnifier.registerOre(new ItemStack(Items.SNOWBALL, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Snow, 907200L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.SNOW, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Snow, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.GLOWSTONE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glowstone, 14515200L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.REDSTONE_LAMP, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glowstone, 14515200L), new MaterialStack(Materials.Redstone, OrePrefix.dust.materialAmount * 4L)));
        //OreDictUnifier.registerOre(ModHandler.getModItem("Forestry", "craftingMaterial", 1, 5), new ItemMaterialInfo(new MaterialStack(Materials.Ice, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ICE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Ice, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.PACKED_ICE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Ice, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Items.CLAY_BALL, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Clay, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.CLAY, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Clay, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.HARDENED_CLAY, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Clay, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STAINED_HARDENED_CLAY, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Clay, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.BRICK_BLOCK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Clay, M)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.nuclear, NuclearResourceType.uranium_238, 1), new ItemMaterialInfo(new MaterialStack(Materials.Uranium, M)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.nuclear, NuclearResourceType.uranium_235, 1), new ItemMaterialInfo(new MaterialStack(Materials.Uranium235, M)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.nuclear, NuclearResourceType.plutonium, 1), new ItemMaterialInfo(new MaterialStack(Materials.Plutonium, M)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.nuclear, NuclearResourceType.small_uranium_235, 1), new ItemMaterialInfo(new MaterialStack(Materials.Uranium235, 403200L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.nuclear, NuclearResourceType.small_plutonium, 1), new ItemMaterialInfo(new MaterialStack(Materials.Plutonium, 403200L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.iron, 1), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 1814400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.gold, 1), new ItemMaterialInfo(new MaterialStack(Materials.Gold, 1814400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.bronze, 1), new ItemMaterialInfo(new MaterialStack(Materials.Bronze, 1814400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.copper, 1), new ItemMaterialInfo(new MaterialStack(Materials.Copper, 1814400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.tin, 1), new ItemMaterialInfo(new MaterialStack(Materials.Tin, 1814400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.lead, 1), new ItemMaterialInfo(new MaterialStack(Materials.Lead, 1814400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.casing, CasingResourceType.steel, 1), new ItemMaterialInfo(new MaterialStack(Materials.Steel, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Items.BOOK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Paper, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Items.WRITTEN_BOOK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Paper, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Items.WRITABLE_BOOK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Paper, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Items.ENCHANTED_BOOK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Paper, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Items.GOLDEN_APPLE, 1, 1), new ItemMaterialInfo(new MaterialStack(Materials.Gold, OrePrefix.block.materialAmount * 8L)));
        OreDictUnifier.registerOre(new ItemStack(Items.GOLDEN_APPLE, 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Gold, OrePrefix.ingot.materialAmount * 8L)));
        OreDictUnifier.registerOre(new ItemStack(Items.GOLD_NUGGET, 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Gold, OrePrefix.nugget.materialAmount * 8L)));
        OreDictUnifier.registerOre(new ItemStack(Items.SPECKLED_MELON, 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Gold, OrePrefix.nugget.materialAmount * 8L)));
        OreDictUnifier.registerOre(new ItemStack(Items.MINECART, 1), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 18144000L)));
        OreDictUnifier.registerOre(new ItemStack(Items.CAULDRON, 1), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 25401600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.IRON_BARS, 8, W), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 10886400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2TEItem(TeBlock.iron_furnace, 1), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 18144000L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Gold, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 7257600L)));
        OreDictUnifier.registerOre(ModHandler.getModItem("Railcraft", "tile.railcraft.anvil", 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Steel, 108864000L)));
        OreDictUnifier.registerOre(ModHandler.getModItem("Railcraft", "tile.railcraft.anvil", 1, 1), new ItemMaterialInfo(new MaterialStack(Materials.Steel, 72576000L)));
        OreDictUnifier.registerOre(ModHandler.getModItem("Railcraft", "tile.railcraft.anvil", 1, 2), new ItemMaterialInfo(new MaterialStack(Materials.Steel, 36288000L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ANVIL, 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 108864000L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ANVIL, 1, 1), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 72576000L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ANVIL, 1, 2), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 36288000L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.HOPPER, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 18144000L), new MaterialStack(Materials.Wood, 29030400L)));
        OreDictUnifier.registerOre(ModHandler.IC2.getIC2Item(ItemName.fluid_cell, 1), new ItemMaterialInfo(new MaterialStack(Materials.Tin, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.TRIPWIRE_HOOK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Iron, OrePrefix.ring.materialAmount * 2L), new MaterialStack(Materials.Wood, M)));
        OreDictUnifier.registerOre(new ItemStack(Items.GLASS_BOTTLE), new ItemMaterialInfo(new MaterialStack(Materials.Glass, M)));
        OreDictUnifier.registerOre(new ItemStack(Items.POTIONITEM, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glass, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STAINED_GLASS, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glass, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.GLASS, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glass, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STAINED_GLASS_PANE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glass, 1360800L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.GLASS_PANE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Glass, 1360800L)));
        OreDictUnifier.registerOre(new ItemStack(Items.CLOCK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Gold, 14515200L), new MaterialStack(Materials.Redstone, M)));
        OreDictUnifier.registerOre(new ItemStack(Items.COMPASS, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Iron, 14515200L), new MaterialStack(Materials.Redstone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.BEACON, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.NetherStar, M), new MaterialStack(Materials.Obsidian, 10886400L), new MaterialStack(Materials.Glass, 18144000L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ENCHANTING_TABLE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Diamond, 7257600L), new MaterialStack(Materials.Obsidian, 14515200L), new MaterialStack(Materials.Paper, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ENDER_CHEST, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.EnderEye, M), new MaterialStack(Materials.Obsidian, 29030400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.BOOKSHELF, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Paper, 32659200L), new MaterialStack(Materials.Wood, 21772800L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.LEVER, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, M), new MaterialStack(Materials.Wood, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.ICE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Ice, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.PACKED_ICE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Ice, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.SNOW, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Snow, M)));
        OreDictUnifier.registerOre(new ItemStack(Items.SNOWBALL, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Snow, 907200L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.SNOW_LAYER, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Snow, -1)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 8), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 2), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 10), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 3), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 11), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 5), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_SLAB, 1, 13), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 1814400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.FURNACE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 29030400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONEBRICK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, M)));

        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 0), new ItemMaterialInfo(new MaterialStack(Materials.Stone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 1), new ItemMaterialInfo(new MaterialStack(Materials.GraniteBlack, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 2), new ItemMaterialInfo(new MaterialStack(Materials.GraniteBlack, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 5), new ItemMaterialInfo(new MaterialStack(Materials.Diorite, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 6), new ItemMaterialInfo(new MaterialStack(Materials.Diorite, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 3), new ItemMaterialInfo(new MaterialStack(Materials.Andesite, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE, 1, 4), new ItemMaterialInfo(new MaterialStack(Materials.Andesite, M)));

        OreDictUnifier.registerOre(new ItemStack(Blocks.COBBLESTONE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.MOSSY_COBBLESTONE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_BUTTON, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STONE_PRESSURE_PLATE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.LADDER, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.WOODEN_BUTTON, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.WOODEN_PRESSURE_PLATE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.OAK_FENCE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 5443200L)));
        OreDictUnifier.registerOre(new ItemStack(Items.BOWL, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, M)));
        OreDictUnifier.registerOre(new ItemStack(Items.SIGN, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 7257600L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.CHEST, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 29030400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.TRAPPED_CHEST, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 32659200L), new MaterialStack(Materials.Iron, OrePrefix.ring.materialAmount * 2L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.REDSTONE_TORCH, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 1814400L), new MaterialStack(Materials.Redstone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.NOTEBLOCK, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 29030400L), new MaterialStack(Materials.Redstone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.JUKEBOX, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 29030400L), new MaterialStack(Materials.Diamond, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.CRAFTING_TABLE, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Wood, 14515200L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.PISTON, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 14515200L), new MaterialStack(Materials.Wood, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.STICKY_PISTON, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 14515200L), new MaterialStack(Materials.Wood, 10886400L)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.DISPENSER, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 25401600L), new MaterialStack(Materials.Redstone, M)));
        OreDictUnifier.registerOre(new ItemStack(Blocks.DROPPER, 1, W), new ItemMaterialInfo(new MaterialStack(Materials.Stone, 25401600L), new MaterialStack(Materials.Redstone, M)));
    }
}