pause
COPY \\?\%1 "DULL\"
COPY \\?\%1 "FINE\"
COPY \\?\%1 "FLINT\"
COPY \\?\%1 "FLUID\"
COPY \\?\%1 "LAPIS\"
COPY \\?\%1 "LIGNITE\"
COPY \\?\%1 "NONE\"
COPY \\?\%1 "PAPER\"
COPY \\?\%1 "POWDER\"
COPY \\?\%1 "QUARTZ\"
COPY \\?\%1 "ROUGH\"
COPY \\?\%1 "SAND\"